Repository The-Fleet/fleetstation13, pull requests merged in 2022-01, with the labels that each got.

#3 Automatic TGS DMAPI Update
  code/modules/tgs/v3210/api.dm
Labels: Tools

#7 AdminText Update
  config/admins.txt
Labels: Administration

#8 Config Changes
  config/config.txt
  config/game_options.txt
  config/maps.txt
  config/motd.txt
Labels: Quality of Life
